### ISSUE TITLE
[想法]等待linux背景模糊插件发布后，希望兼容Linux

### ISSUE THREAD

**Issue by mo-jinran** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#12]
修改了窗口颜色为透明，并使用了xprop命令给窗口背景模糊效果，感觉可以兼容Linux
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/66980784/4ac79f2d-f102-4920-9862-b602103d7edf)

**Comment by MUKAPP** [comment]
好

**Comment by mo-jinran** [comment]
好消息是Linux并没有屏蔽DevTools,所以开发会更舒服一些吧

**Comment by mo-jinran** [comment]
[Linux | 背景毛玻璃] https://github.com/mo-jinran/linux-qqnt-background-blur

**Comment by MUKAPP** [comment]
有没有办法区分windows还是linux（）

**Comment by mo-jinran** [comment]
可以使用提供的betterQQNT.os.platform
渲染进程在window对象上有一份betterQQNT对象
主进程在onLoad函数第二个参数就是

**Comment by mo-jinran** [comment]
```
if (LiteLoader.os.platform == "win32") {
    // Windows
}
if (LiteLoader.os.platform == "linux") {
    // Linux
}
if (LiteLoader.os.platform == "darwin") {
    // MacOS
}
```

**Comment by MUKAPP** [comment]
应该是好了，但是我用的GNOME，不知道具体效果（）

**Comment by mo-jinran** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/66980784/285ab031-28ce-46a5-a943-bd5ba65a2bff)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/66980784/220abd49-7ba5-42ea-a325-86fe559335a3)

**Comment by mo-jinran** [comment]
用了，除了sidebar不透明（不知道是不是故意的）没什么问题，设置界面还没看（毛玻璃插件有点bug）

**Comment by mo-jinran** [comment]
选择表情的小弹窗不透明（widows下有一点透明效果的）

**Comment by MUKAPP** [comment]
![7665A62DA1161994F67D61C9BD803562](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/1a2af934-c038-4339-ae06-ebff110e64e1)
sidebar不是故意的，可能跟windows版不太一样，我再改改（）

**Comment by mo-jinran** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/66980784/6015cfd2-03d2-41d0-ae29-52a3cd88d95a)
好友通知列表，鼠标hover效果

**Comment by mo-jinran** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/66980784/6036ffea-8ace-4876-a188-223cafd9e0bb)
好友通知列表的hover效果

**Comment by mo-jinran** [comment]
还有那个搜索框点了之后没去掉背景

**Comment by MUKAPP** [comment]
好了
linux版qq的骚操作比windows版还离谱
那个搜索结果下面另外又用了个div加的背景，我还纳闷半天
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/efab62b9-5bc3-4357-8864-bf5ead87d6f9)

**Comment by gfhdhytghd** [comment]
我建议参考cider的背景透明度来写linux兼容，cider的背景透明度在我用过的桌面上基本都能跑起来，包括wayland模式下

![image](https://github.com/user-attachments/assets/96301f54-af43-4b18-962c-59893ad267af)
