### ISSUE TITLE
缺少透明效果设置

### ISSUE THREAD

**Issue by CMHopeSunshine** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#14]
在`设置-通用`中并没有`其他`选项

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/63870437/7ff23639-2eff-45fc-bf09-7dcbf7a835ea)

QQNT版本是最新的，如下图：

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/63870437/1075ef85-258b-4bf2-bb05-14c6fb8f0e0a)

**Comment by MUKAPP** [comment]
![7665A62DA1161994F67D61C9BD803562](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/5e90827f-bd9b-41f1-b28c-cd3b1885986b)
我应该是忘了点什么（）
你是win10吗（）

**Comment by MUKAPP** [comment]
win10好像没有这个功能

**Comment by CMHopeSunshine** [comment]
好的，了解了
