### ISSUE TITLE
主题透明效果设置

### ISSUE THREAD

**Issue by Uincsrh** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#18]
color不支持带有透明通道的颜色
用滑块设置透明效果感觉不错
我也不怎么会css，这里仅提供参考

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/88591153/97715097-aaa1-47c6-bc9a-45ccbf978a57)

### settings.html中添加滑块
`<div class="vertical-list-item top-box">
                <h2>主题背景透明</h2>
                <input type="range" value="1" min="0" max="10" step="1"
                    class="q-button q-button--small q-button--secondary pick-opacity" style="width: 460px;" />
            </div>`

`<div class="vertical-list-item top-box">
                <h2>主题颜色透明</h2>
                <input type="range" value="1" min="0" max="9" step="1"
                    class="q-button q-button--small q-button--secondary pick-opacity-1" style="width: 460px;" />
            </div>`

### renderer.js中添加代码（// 打开设置界面时触发）
参考pick-color的代码
`// 主题背景透明
    const themeOpacity = settings.themeOpacity;
    // 给pick-opacity(input)设置默认值
    const pickOpacity = view.querySelector(".pick-opacity");
    pickOpacity.value = themeOpacity;
    // 给pick-opacity(input)添加事件监听
    pickOpacity.addEventListener("change", (event) => {
        // 修改settings的themeOpacity值
        settings.themeOpacity = event.target.value;
        // 将修改后的settings保存到settings.json
        mspring_theme.setSettings(settings);
    });`

`// 主题颜色透明
    const themeOpacity1 = settings.themeOpacity1;
    // 给pick-opacity-1(input)设置默认值
    const pickOpacity1 = view.querySelector(".pick-opacity-1");
    pickOpacity1.value = themeOpacity1;
    // 给pick-opacity-1(input)添加事件监听
    pickOpacity1.addEventListener("change", (event) => {
        // 修改settings的themeOpacity1值
        settings.themeOpacity1 = event.target.value;
        // 将修改后的settings保存到settings.json
        mspring_theme.setSettings(settings);
    });`
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/88591153/28825e64-b04d-4122-bc3b-acf65b836204)

### main.js中添加代码（// 更新样式）
`--theme-color: color-mix(in oklch, ${themeColor}, transparent ${themeOpacity1}0%);`
`--theme-opacity: color-mix(in oklch, #FFFFFF, transparent ${themeOpacity}0%);`

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/88591153/f1b26928-7d72-455b-ba22-0701793b7799)

### main.js中添加代码（// 加载插件时触发）
`"themeOpacity": "3",
            "themeOpacity1": "7",`

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/88591153/2036e10a-5b13-4807-8cf6-1d1959cd685c)

### style.css中修改代码（ /* 浅色模式 */）
`background: var(--theme-opacity) !important;`
深色模式需要在添加一个滑块

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/88591153/16e3fc8b-170d-48c5-b66f-9d393ac58fdd)

**Comment by MUKAPP** [comment]
厉害的
不过我感觉主题色加透明度不太好（）
背景色透明度可以，但是得考虑内容的可见度
一会儿看看

**Comment by Bill-Haku** [comment]
话说macOS版有没有可能做一下半透明的效果呢？

**Comment by MUKAPP** [comment]
最新的代码加了背景颜色的透明
