### ISSUE TITLE
macOS下群成员处背景与实际成员列表产生偏移

### ISSUE THREAD

**Issue by baysonfox** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#19]
![CleanShot 2023-07-09 at 15 07 54](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/23008133/377c504f-b933-4296-b4f4-9371c780018b)
![CleanShot 2023-07-09 at 15 11 56](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/23008133/47ed32bb-d945-4449-b8b4-e26ec71f5e2f)

如图，左侧聊天列表里也有偏移

**Comment by MUKAPP** [comment]
看起来跟linux的情况一样，我试着用之前修linux的办法修一下吧，没有mac我看不到效果（）

**Comment by MUKAPP** [comment]
试一下main最新的代码

**Comment by baysonfox** [comment]
git pull了 没问题(

**Comment by MUKAPP** [comment]
okk
