### ISSUE TITLE
如何做到描述中的截图效果呢？

### ISSUE THREAD

**Issue by tslace** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#21]
win11
最新版QQNT
开启透明后也聊天界面也无法达到毛玻璃的透明感。。是需要自己改吗？
谢谢。

**Comment by MUKAPP** [comment]
截图看看

**Comment by tslace** [comment]
我错了。。。刚发完问题我去重装了遍插件。。。就可以了。。。昨晚折腾了半天都是不行的...
真好看~~黑夜模式。。谢谢大佬~~
