### ISSUE TITLE
第三方插件配置界面这儿怎么弄成半透明呀

### ISSUE THREAD

**Issue by lamprose** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#22]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/29279979/d8aac3ac-c43f-4cc5-ac58-ad85f807b554)
我尝试在这个元素上添加个mspring_theme的class就可以了
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/29279979/18302dae-3438-43e5-9aec-a2071144c7a3)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/29279979/f60d18fe-d326-451e-9668-a54c8bda34a6)

**Comment by MUKAPP** [comment]
最新的代码适配了一些常规插件
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/81f58ad9-2215-4e52-b7b5-a0c6ac277230)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/6809a5f8-e587-4b40-a1a4-e23839c3e6bd)

**Comment by lamprose** [comment]
嗯嗯  更新可以了
