### ISSUE TITLE
大佬为何装好后没有配置项呢？

### ISSUE THREAD

**Issue by tslace** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#24]
![QQ截图20230713212605](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/84954133/132a24f5-4b09-4432-8c94-e29c8375ed84)
我看文件里应该有个调整透明度的滑块的。。

**Comment by MUKAPP** [comment]
好了，更新下主题
