### ISSUE TITLE
独立窗口无mica半透明效果

### ISSUE THREAD

**Issue by AduitSSH** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#26]
RT

**Comment by AduitSSH** [comment]
系统：Windows 11 22H2 22621.1992
QQ：9.9.1.15034
QQNTim

**Comment by MUKAPP** [comment]
win端tx并没有给独立的聊天窗口mica效果，即使网页的背景全部删掉也是白色的，故暂时无法修复。

**Comment by AduitSSH** [comment]
> win端tx并没有给独立的聊天窗口mica效果，即使网页的背景全部删掉也是白色的，故暂时无法修复。

如果有人搁tx官方群反馈说独立窗口没有半透明的话也许tx会安排？

**Comment by MUKAPP** [comment]
照目前的情况来看tx官方并没有打算做聊天窗口半透明（包括默认的非独立窗口也只是侧栏背景半透明），如果主动去提反而可能会打草惊蛇。

**Comment by PRO-2684** [comment]
> win端tx并没有给独立的聊天窗口mica效果，即使网页的背景全部删掉也是白色的，故暂时无法修复。

可以参考 [Linux 背景毛玻璃插件的 main.js](https://github.com/mo-jinran/linux-qqnt-background-blur/blob/v3/src/main.js) hook `BrowserWindow` 来强制开启半透明

**Comment by MUKAPP** [comment]
> 可以参考 [Linux 背景毛玻璃插件的 main.js](https://github.com/mo-jinran/linux-qqnt-background-blur/blob/v3/src/main.js) hook `BrowserWindow` 来强制开启半透明

结果如下
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/11274d49-1f04-42b5-8e82-a829651f32d7)

**Comment by PRO-2684** [comment]
> 结果如下 ![image](https://user-images.githubusercontent.com/41848070/261961660-11274d49-1f04-42b5-8e82-a829651f32d7.png)

这样子再加个 `background` 和 `backdrop-filter` 应该就不错了

**Comment by MUKAPP** [comment]
> 这样子再加个 `background` 和 `backdrop-filter` 应该就不错了

`backdrop-filter` 并不能模糊网页外的东西

**Comment by MUKAPP** [comment]
见最新版
