### ISSUE TITLE
[ADD] QQNTim 2.2.0直接安装支持

### ISSUE THREAD

**Issue by AduitSSH** [MUKAPP/LiteLoaderQQNT-MSpring-Theme#27]
有可能某些地方调用了不需要的CSS？
跟mainfest.json放在一起就行
QQNTim 2.2.0 测试可用
在QQNTim下使用，推荐配合 系统主题色、Gaussian UI 两个插件一起使用，不然会有一点点奇奇怪怪的小问题

文件名：qqntim.json
格式：UTF-8
内容：
`{
    "manifestVersion": "2.0",
    "id": "mspring_theme",
    "name": "MSpring Theme",
    "author": "MUKAPP",
    "description": "QQNTim 主题，优雅 · 粉粉 · 细致",
    "version": "1.0.3",
    "requirements": 
    {
        "os": [{ "platform": "win32"}]
    },
    "injections": [
        {
            "type": "main",
            "stylesheet": "style.css",
            "script": "main.js"
        },
        {
            "type": "renderer",
            "stylesheet": "style.css",
            "script": "renderer.js"
        },
        {
            "type": "preload",
            "stylesheet": "style.css",
            "script": "preload.js"
        }
    ]
}
`

在QQNTim上安装后效果图：
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/50974047/a50772ad-5616-4a66-b5c6-d0ea80a02c16)

**Comment by MUKAPP** [comment]
主题暂时不打算适配QQNTim
不过这个issue可以留着，如果有人想在QQNTim上用本主题的话可以做参考
